import os
import shutil

"""
I think this has some problems moving information right now!! delete is working correctly
"""


# Deletes the finetuning data(data generated by trainer gui)
def delete_predictions():
    current_dir = os.path.dirname(os.path.abspath(__file__))

    prediction_folder = os.path.join(current_dir,'..')
    prediction_folder = os.path.join(prediction_folder,'data')

    prediction_folders = os.listdir(prediction_folder)
    for x in prediction_folders:
        folder_path = os.path.join(prediction_folder, x)
        for file in os.listdir(folder_path):
            file_path = os.path.join(folder_path, file)
            for i in os.listdir(file_path):
                os.remove(os.path.join(file_path,i))
            #print(f"Removed {file_path}")

# Passes information from the finetunning to the normal training
def take_information():
    current_dir = os.path.dirname(os.path.abspath(__file__))

    prediction_folder = os.path.join(current_dir,'..')
    prediction_folder = os.path.join(prediction_folder,'data')

    prediction_folders = os.listdir(prediction_folder)
    data_folder = os.path.join(os.path.join(current_dir, "data"))
    # Create the prediction folder if it does not exist
    os.makedirs(data_folder, exist_ok=True)
    
    for x in prediction_folders:
        for file in os.listdir(prediction_folder + "/" + x):
            src = prediction_folder + "/" + x + "/" + file
            dest = data_folder + "/" + x + "/" + file
            shutil.move(src, dest)
            print(f"Moved {src} to {dest}")

def pass_information():
    delete_predictions() ## delete new data that might be incorect
    
    current_dir = os.path.dirname(os.path.abspath(__file__))

    prediction_folder = os.path.join(current_dir,'..')
    prediction_folder = os.path.join(prediction_folder,'data')

    prediction_folders = os.listdir(prediction_folder)
    data_folder = prediction_folder

    prediction_folder = os.path.join(os.path.join(current_dir, "data"))
    # Create the prediction folder if it does not exist
    os.makedirs(data_folder, exist_ok=True)
    
    for x in prediction_folders:
        for file in os.listdir(prediction_folder + "/" + x):
            src = prediction_folder + "/" + x + "/" + file
            dest = data_folder + "/" + x + "/" + file
            shutil.move(src, dest)
            print(f"Moved {src} to {dest}")
#take_information()
#delete_predictions()