"""
Useful to manage the information generated by the trainer gui
"""
import os
import shutil

# Deletes the finetuning data(data generated by trainer gui)
def delete_predictions():
    current_dir = os.path.dirname(os.path.abspath(__file__))

    prediction_folder = os.path.join(current_dir,'square_data')
    prediction_folders = os.listdir(prediction_folder)
    for x in prediction_folders:
        folder_path = os.path.join(prediction_folder, x)
        for file in os.listdir(folder_path):
            file_path = os.path.join(folder_path, file)
            os.remove(file_path)
            #print(f"Removed {file_path}")

# Passes information from the finetunning to the normal training
def pass_information():
    current_dir = os.path.dirname(os.path.abspath(__file__))

    prediction_folder = os.path.join(current_dir,'square_data')
    prediction_folders = os.listdir(prediction_folder)
    data_folder = os.path.join(os.path.join(os.path.join(current_dir, ".."), "tactic_to_fen"), 'data')
    for x in prediction_folders:
        for file in os.listdir(prediction_folder + "/" + x):
            src = prediction_folder + "/" + x + "/" + file
            dest = data_folder + "/" + x + "/" + file
            shutil.move(src, dest)
            print(f"Moved {src} to {dest}")
#delete_predictions()